[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
optimizer = true
optimizer_runs = 1
bytecode_hash = "none"
cbor_metadata = false
evm_version = "prague"
solc_version = "0.8.35"

[lint]
lint_on_build = false
