[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
optimizer = true
optimizer_runs = 1
bytecode_hash = "none"
cbor_metadata = false
evm_version = "prague"
solc_version = "0.8.37"

# Keep the Yul statement order to decrease the program size.
# The empty optimizer sequence gives 60 bytes. The default sequence gives 85 bytes.
# The compiler still applies peephole optimization.
[profile.default.optimizer_details]
yul = true
yulDetails = { optimizerSteps = ":" }

[lint]
lint_on_build = false
