import { readFile, writeFile } from "node:fs/promises";

const artifactUrl = new URL(
	"../out/Ghostcall.yul/Ghostcall.json",
	import.meta.url,
);
const outputUrl = new URL("../src/sdk/generated/initcode.ts", import.meta.url);

const artifact = JSON.parse(await readFile(artifactUrl, "utf8")) as {
	bytecode?: { object?: unknown };
};
const bytecode = artifact.bytecode?.object;

if (typeof bytecode !== "string" || !/^0x(?:[0-9a-fA-F]{2})+$/.test(bytecode)) {
	throw new TypeError(`Missing or invalid bytecode in ${artifactUrl.pathname}`);
}

await writeFile(
	outputUrl,
	`// This file is generated by scripts/generate-sdk-initcode.ts.
// Run npm run build:contracts after changing src/Ghostcall.yul.

export const ghostcallInitcode =
\t${JSON.stringify(bytecode)} as const;
`,
);
